print("Hello World.")
var = 2018
print("Today is Monday the 5th of November", var)
print("My name is Damian Vega.\n"*3)
# print(7+8)
# print(7-8)
# print(7*2)
# print(30/5)
# print(5**2)
# print(7/8)